### ISSUE TITLE
Python SDK is not working

### ISSUE THREAD

**Issue by ghost** [messagemedia/messages-python-sdk#6]
Python example with my credentials and my phone number (+61 and so on):
```
root@ext-somehost-01:~  # ./sms.py
INFO:message_media_messages.controllers.messages_controller:create_send_messages called.
INFO:message_media_messages.controllers.messages_controller:Preparing query URL for create_send_messages.
INFO:message_media_messages.controllers.messages_controller:Preparing headers for create_send_messages.
INFO:message_media_messages.controllers.messages_controller:Preparing and executing request for create_send_messages.
INFO:message_media_messages.controllers.messages_controller:Merging global headers with endpoint headers for create_send_messages.
INFO:message_media_messages.controllers.messages_controller:Wrapping request and response in a context object for create_send_messages.
INFO:message_media_messages.controllers.messages_controller:Validating response for create_send_messages.
ERROR:message_media_messages.controllers.messages_controller:HTTP response not OK.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/message_media_messages/controllers/messages_controller.py", line 359, in create_send_messages
    self.validate_response(_context)
  File "build/bdist.linux-x86_64/egg/message_media_messages/controllers/base_controller.py", line 120, in validate_response
    raise APIException('HTTP response not OK.', context)
APIException: HTTP response not OK.
Traceback (most recent call last):
  File "./sms.py", line 23, in <module>
    result = messages_client.create_send_messages(body)
  File "build/bdist.linux-x86_64/egg/message_media_messages/controllers/messages_controller.py", line 359, in create_send_messages
  File "build/bdist.linux-x86_64/egg/message_media_messages/controllers/base_controller.py", line 120, in validate_response
message_media_messages.exceptions.api_exception.APIException: HTTP response not OK.
```

**Comment by JamesDale** [comment]
Hi @alexizmailov,

It looks as though this could be an authentication issue. Did you want to double check your api keys, secret and mobile number? Otherwise feel free to email me your code at james.dale@messagemedia.com.au and I'll take a look into it for you.

Thanks.

**Comment by ghost** [comment]
My credentials are definitely correct, they work with [soap-bash](https://github.com/messagemedia/messagemedia-soap-api-bash-sdk) and [soap-python](https://github.com/messagemedia/messagemedia-soap-api-python-sdk) and I copy-pasted them here, not just typed them. The code is taken from example in Readme.md
```python
# Configuration parameters and credentials
from message_media_messages.message_media_messages_client import MessageMediaMessagesClient
import json

auth_user_name = 'MY_KEY' # The username to use with basic authentication
auth_password = 'MY_PASSWORD' # The password to use with basic authentication

client = MessageMediaMessagesClient(auth_user_name, auth_password)

messages_client = client.messages

body_value = '''{
    "messages":[
        {
            "content":"My first message",
            "destination_number":"+61_my_number"
        }
    ]
}'''

body = json.loads(body_value)

result = messages_client.create_send_messages(body)
```
Just these two return "HTTP response not OK" - python and ruby sdks.

**Comment by JamesDale** [comment]
The SOAP API Keys won't work with the REST SDKs, your REST credentials have been previously sent to a 'Patrick C'. If you would like to get REST credentials please contact support https://www.messagemedia.com.au/contact-us

**Comment by ghost** [comment]
Ah, that's why... ok, understood that, thank you.
Just in case - it's not obvious from docs that those keys are different and SOAP key doesn't work with REST...

**Comment by JamesDale** [comment]
No worries! Let me know if you get stuck :)
